name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install CPU PyTorch
        run: |
          pip install torch==2.2.2 torchvision==0.17.2 \
          --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest tests/

      - name: Build Docker image
        run: docker build -t cats-dogs-api .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag cats-dogs-api ${{ secrets.DOCKER_USERNAME }}/cats-dogs-api:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cats-dogs-api:latest

      - name: Run container for smoke testing
        run: |
          docker run -d -p 8000:8000 --name smoke-test-container ${{ secrets.DOCKER_USERNAME }}/cats-dogs-api:latest
          sleep 5

      - name: Install requests
        run: pip install requests

      - name: Run smoke test
        run: python smoke_check.py

      - name: Stop container
        run: docker stop smoke-test-container